#:kivy 1.9.0

<FileManager@GridLayout>:
	cols: 1
	canvas:
		Color:
			rgba: .5, .5, 1, .5
		Rectangle:
			pos: self.pos
			size: self.size
	filelist: d_filelist
	titlelabel: d_titlelabel
	TitleLabel:
		id: d_titlelabel
		filelist: d_filelist
	ScrollView:
		scroll_type: ['bars']
		do_scroll: True, True
		bar_width: 5
		canvas.before:
			Color:
				rgba: .5, .5, .5, .5
			Line:
				rectangle: self.x, self.y, self.width, self.height
		FileList:
			id: d_filelist
