#:kivy 1.9.0
#:import ttf gui.font.ttf
#:import OperateList gui.operatelist

<OperateButton>:
	color: 0, 0, 0, 1
	font_name: ttf
	font_size: 16
	text_size: self.size

	size_hint: 1, None
	height: 40
	
	on_release: self.event(self) if self.collide_point(self.last_touch.x, self.last_touch.y) and hasattr(self, 'event') and hasattr(self.event, '__call__') else None

<OperateList>:
	rows: 1
	size_hint: 1, None
	height: 40